WebUI/Controllers/TenantRenewalController.cs
using BL;
using DomainObject;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebUI.Attributes;
using WebUI.Models;

namespace WebUI.Controllers
{
    [SessionExpire]
    [Authorize]

    public class TenantRenewalController : Controller
    {
        // GET: TenantRenewal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Update(int id)
        {
            var _tenantDO = TenantRenewalBL.GetTenantRenewalById(id);
            var _progress = Computation.ProgressPercentage(_tenantDO);
            // populate statuses
            var _statuses = GenerateStatus();

            TenantRenewalView _tenantmodel = PopulateTenantRenewalView(_tenantDO, _progress, _statuses);
            return View(_tenantmodel);
        }

        private TenantRenewalView PopulateTenantRenewalView(TenantRenewal _tenantDO, double _progress, List<Status> _statuses)
        {
            TenantRenewalView _tenantmodel = new TenantRenewalView()
            {
                Id = _tenantDO.Id,
                TenantId = _tenantDO.TenantId,
                Expiry = _tenantDO.ExpiryDate,
                MyProperty = _tenantDO.MyProperty,
                Name = _tenantDO.Name,
                Area = _tenantDO.Area,
                LeasingStatus = _tenantDO.LeasingStatus,
                LeasingStatusString = ConvertStatusToString(_tenantDO.LeasingStatus),
                //RenewalRequirements = _tenantDO.RenewalRequirements,
                ContractSignedNotarized = _tenantDO.ContractSignedNotarized,
                BalancesPaid = _tenantDO.BalancesPaid,
                RenewalSigned = _tenantDO.RenewalSigned,
                Underperformer = _tenantDO.Underperformer,
                Category = _tenantDO.Category,
                CategorySpecialist = _tenantDO.CategorySpecialist,
                UnderperformerYears = _tenantDO.UnderperformerYears,
                UnderperformerMonth = _tenantDO.UnderperformerMonth,
                CurrentRentBase = _tenantDO.CurrentRentBase,
                CurrentMGR = _tenantDO.CurrentMGR,
                HistoricalPerformanceYear1 = _tenantDO.HistoricalPerformanceYear1,
                AveSalesPerSQMYear1 = _tenantDO.AveSalesPerSQMYear1,
                AveEffectiveRentYear1 = _tenantDO.AveEffectiveRentYear1,
                HistoricalPerformanceYear2 = _tenantDO.HistoricalPerformanceYear2,
                AveSalesPerSQMYear2 = _tenantDO.AveSalesPerSQMYear2,
                AveEffectiveRentYear2 = _tenantDO.AveEffectiveRentYear2,
                HistoricalPerformanceYear3 = _tenantDO.HistoricalPerformanceYear3,
                AveSalesPerSQMYear3 = _tenantDO.AveSalesPerSQMYear3,
                AveEffectiveRentYear3 = _tenantDO.AveEffectiveRentYear3,
                HistoricalPerformanceYear4 = _tenantDO.HistoricalPerformanceYear4,
                AveSalesPerSQMYear4 = _tenantDO.AveSalesPerSQMYear4,
                AveEffectiveRentYear4 = _tenantDO.AveEffectiveRentYear4,
                LeasingCategorySpecialistRemarks = _tenantDO.LeasingCategorySpecialistRemarks,
                LeasingReviewDone = _tenantDO.LeasingReviewDone,
                LeasingHeadRemarks = _tenantDO.LeasingHeadRemarks,
                LeasingHeadVerified = _tenantDO.LeasingHeadVerified,
                DesignStatus = _tenantDO.DesignStatus,
                DesignStatusString = ConvertStatusToString(_tenantDO.DesignStatus),
                ForMajorRenovation = _tenantDO.ForMajorRenovation,
                DesignRemarks = _tenantDO.DesignRemarks,
                DesignReviewDone = _tenantDO.DesignReviewDone,
                DesignHeadVerified = _tenantDO.DesignHeadVerified,
                OperationStatus = _tenantDO.OperationStatus,
                OperationStatusString = ConvertStatusToString(_tenantDO.OperationStatus),
                OperationFacilitiesRemarks = _tenantDO.OperationFacilitiesRemarks,
                OperationFacilitiesReviewDone = _tenantDO.OperationFacilitiesReviewDone,
                OperationTenancyRemarks = _tenantDO.OperationTenancyRemarks,
                OperationsTenancyReviewDone = _tenantDO.OperationsTenancyReviewDone,
                OperationHouseKeepingRemarks = _tenantDO.OperationHouseKeepingRemarks,
                OperationHouseKeepingReviewDone = _tenantDO.OperationHouseKeepingReviewDone,
                OperationSecurityRemarks = _tenantDO.OperationSecurityRemarks,
                OperationSecurityReviewDone = _tenantDO.OperationSecurityReviewDone,
                OperationsHeadVerified = _tenantDO.OperationsHeadVerified,
                ITStatus = _tenantDO.ITStatus,
                ITStatusString = ConvertStatusToString(_tenantDO.ITStatus),
                POSSystemAgreement = _tenantDO.POSSystemAgreement,
                DailySalesReporting = _tenantDO.DailySalesReporting,
                ITRemarks = _tenantDO.ITRemarks,
                ITReviewDone = _tenantDO.ITReviewDone,
                ITHeadVerified = _tenantDO.ITHeadVerified,
                FinanceStatus = _tenantDO.FinanceStatus,
                FinanceStatusString = ConvertStatusToString(_tenantDO.FinanceStatus),
                UnpaidCharges = _tenantDO.UnpaidCharges,
                AdvanceRentPaid = _tenantDO.AdvanceRentPaid,
                SecurityDepositPaid = _tenantDO.SecurityDepositPaid,
                FinanceReviewDone = _tenantDO.FinanceReviewDone,
                FinanceHeadVerified = _tenantDO.FinanceHeadVerified,
                AuditStatus = _tenantDO.StatusStatus,
                AuditStatusString = ConvertStatusToString(_tenantDO.StatusStatus),
                AuditRequirements = _tenantDO.AuditRequirements,
                AuditRemarks = _tenantDO.AuditRemarks,
                AuditReviewDone = _tenantDO.AuditReviewDone,
                AuditHeadVerified = _tenantDO.AuditHeadVerified,
                VPGMStatus = _tenantDO.VPGMStatus,
                VPGMStatusString = ConvertStatusToString(_tenantDO.VPGMStatus),
                VPGMRemarks = _tenantDO.VPGMRemarks,
                VPGMHeadVerified = _tenantDO.VPGMHeadVerified,
                ChecklistStatus = _tenantDO.ChecklistStatus,
                AuditCMSRSubmissions = _tenantDO.AuditCMSRSubmissions,
                AuditTextFileFormat = _tenantDO.AuditTextFileFormat,
                LeasingHeadVerifiedDate = _tenantDO.LeasingHeadVerifiedDate,
                LeasingHeadVerifiedBy = _tenantDO.LeasingHeadVerifiedBy,
                ReviewDate = _tenantDO.ReviewDate,
                ReviewDoneBy = _tenantDO.ReviewDoneBy,
                DesignReviewDoneDate = _tenantDO.DesignReviewDoneDate,
                DesignReviewDoneBy = _tenantDO.DesignReviewDoneBy,
                DesignHeadVerifiedDate = _tenantDO.DesignHeadVerifiedDate,
                DesignHeadVerifiedBy = _tenantDO.DesignHeadVerifiedBy,
                OperationFacilitiesReviewDoneDate = _tenantDO.OperationFacilitiesReviewDoneDate,
                OperationFacilitiesReviewDoneBy = _tenantDO.OperationFacilitiesReviewDoneBy,
                OperationsTenancyReviewDoneDate = _tenantDO.OperationsTenancyReviewDoneDate,
                OperationsTenancyReviewDoneBy = _tenantDO.OperationsTenancyReviewDoneBy,
                OperationHouseKeepingReviewDoneDate = _tenantDO.OperationHouseKeepingReviewDoneDate,
                OperationHouseKeepingReviewDoneBy = _tenantDO.OperationHouseKeepingReviewDoneBy,
                OperationSecurityReviewDoneDate = _tenantDO.OperationSecurityReviewDoneDate,
                OperationSecurityReviewDoneBy = _tenantDO.OperationSecurityReviewDoneBy,
                OperationsHeadVerifiedDate = _tenantDO.OperationsHeadVerifiedDate,
                OperationsHeadVerifiedBy = _tenantDO.OperationsHeadVerifiedBy,
                ITReviewDoneDate = _tenantDO.ITReviewDoneDate,
                ITReviewDoneBy = _tenantDO.ITReviewDoneBy,
                ITHeadVerifiedDate = _tenantDO.ITHeadVerifiedDate,
                ITHeadVerifiedBy = _tenantDO.ITHeadVerifiedBy,
                FinanceReviewDoneDate = _tenantDO.FinanceReviewDoneDate,
                FinanceReviewDoneBy = _tenantDO.FinanceReviewDoneBy,
                FinanceVerifiedDoneDate = _tenantDO.FinanceReviewDoneDate,
                FinanceVerifiedDoneBy = _tenantDO.FinanceReviewDoneBy,
                AuditReviewDoneDate = _tenantDO.AuditReviewDoneDate,
                AuditReviewDoneBy = _tenantDO.AuditReviewDoneBy,
                AuditHeadVerifiedDate = _tenantDO.AuditHeadVerifiedDate,
                AuditHeadVerifiedBy = _tenantDO.AuditHeadVerifiedBy,
                VPGMHeadVerifiedDate = _tenantDO.VPGMHeadVerifiedDate,
                VPGMHeadVerifiedBy = _tenantDO.VPGMHeadVerifiedBy,
                Progress = _progress,
                Statuses = _statuses
            };
            return _tenantmodel;
        }

        private List<Status> GenerateStatus()
        {
            List<Status> statuses = new List<Status>()
            {
                new Status(){ Id = 0, Name = "Completed" },
                new Status(){ Id = 1, Name = "For Renewal"},
                new Status(){ Id = 2, Name = "On Hold"}
            };
            return statuses;
        }

        [HttpPost]
        public ActionResult Update(TenantRenewalView tenantRenewalView)
        {
            TenantRenewal _tenantDO = new TenantRenewal()
            {
                Id = tenantRenewalView.Id,
                TenantId = tenantRenewalView.TenantId,
                ExpiryDate = tenantRenewalView.Expiry,
                MyProperty = tenantRenewalView.MyProperty,
                Name = tenantRenewalView.Name,

WebUI/Views/TenantRenewal/all.cshtml
@model IEnumerable<WebUI.Models.TenantRenewalView>

@{
    ViewBag.Title = "View All Tenants";
}

<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <table id="table-custom-elements" class="row-border" cellspacing="0" width="100">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Tenant Id</th>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Category Specialist</th>
                            <th>Expiry</th>
                            <th>Status</th>
                            <th>Edit</th>
                            <th>Form</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="fixed-action-btn">
        <a href="@Url.Action("Add", "TenantRenewal")" class="btn-floating btn-large">
            <i class="large material-icons">add</i>
        </a>
    </div>
</div>

@section Scripts {
    <script>

        $(document).ready(function () {
            var data = [@Html.Raw(@TempData["reseveList"])];
            var tableCustomElements = $('#table-custom-elements');
            if (tableCustomElements.length) {
                var table = tableCustomElements.DataTable({
                    'data': data,
                    'columnDefs': [{
                        'targets': 0,
                        'searching': true,
                        'orderable': false,
                        'className': 'dataTables-checkbox-column',
                        'render': function (data, type, full, meta) {
                            return '<label><hidden name="id[]" value="'
                                + $('<div/>').text(data).html() + '"><span></span></label>';
                        }
                    }],
                    'language': {
                        'search': '',
                        'searchPlaceholder': 'Enter search term'
                    },
                    'order': [1, 'asc'],
                    'dom': 'ft<"footer-wrapper"l<"paging-info"ip>>',
                    'scrollY': '500px',
                    'scrollCollapse': true,
                    'pagingType': 'full',
                    'drawCallback': function (settings) {
                        var api = this.api();
                        // Add waves to pagination buttons
                        $(api.table().container()).find('.paginate_button').addClass('waves-effect');
                        api.table().columns.adjust();
                    }
                });
            }
    });
    </script>
}
